### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by ItsMaster** [DotwoodMedia/topgg-votes#3]
Would be great if package could support all types also

![image](https://user-images.githubusercontent.com/77050598/204225450-348636e5-2367-4f16-81be-b2b05fd5df48.png)
![image](https://user-images.githubusercontent.com/77050598/204226192-010d2a5a-be27-406c-8c03-217183385e5f.png)

**Comment by DotwoodMedia** [comment]
The package is already quite old, but would soon make a new version with types included :D

**Comment by pxtzel** [comment]
> The package is already quite old, but would soon make a new version with types included :D

Sounds great!

**Comment by DotwoodMedia** [comment]
I made a dev release yesterday with a new version of the package. Tonight I will test further, but you can use it if you want. 
`npm i topgg-votes@dev`

For the documentation, there is already a start at: https://github.com/DotwoodMedia/topgg-votes/blob/develop/README.md

**Comment by DotwoodMedia** [comment]
New version is released
https://github.com/DotwoodMedia/topgg-votes/releases/tag/2.0.1
